name: class_env
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - dask
  - xarray
  - netcdf4
  - h5netcdf
  - zarr
  - rasterio
  - pyproj
  - shapely
  - pystac
  - copernicusmarine
  - gsw
  - seawater
  - matplotlib
  - plotly
  - cartopy
  - cmocean
  - boto3
  - fsspec
  - pyarrow
  - tqdm
  - requests