name: class_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.14
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scipy
  - netcdf4
  - xarray
  - cartopy
  - shapely
  - pyproj
  - cmocean
  - gsw
  - seawater
  - matplotlib
  - bokeh
  - dask
  - pyarrow
  - plotly
  - ipywidgets
  - rasterio
  - copernicusmarine
